# Load packages -----------------------------------------------------------
{
  library(move)
  library(data.table)
  library(tidyverse)
  conflicted::conflict_prefer("filter", "dplyr")
  conflicted::conflict_prefer("lag", "dplyr")
  conflicted::conflict_prefer("select", "dplyr")
  conflicted::conflict_prefer("summarise", "dplyr")
  library(lubridate)
  library(geosphere)
  library(glue)
  library(maps)
  conflicted::conflict_prefer("map", "purrr")
  library(mapdata)
  library(raster)
  library(sp)
  library(rgdal)
  library(geosphere)
  library(dismo)
  library(rgeos)
  library(sf)
  library(recurse)
  library(plotly)
  conflicted::conflict_prefer("layout", "plotly")
  conflicted::conflict_prefer("collapse", "dplyr")
  library(leaftime)
  library(httr)
  library(jsonlite)
  library(leaflet)
  library(leafem)
  library(htmltools)
  library(plyr, warn.conflicts = FALSE)
  conflicted::conflict_prefer("span", "htmltools")
  library(leafpop)
  library(leaflet.extras)
  conflicted::conflict_prefer("config", "httr")
  conflicted::conflict_prefer("flatten", "purrr")
  conflicted::conflict_prefer("hour", "data.table")
  conflicted::conflict_prefer("hour", "lubridate")
  
  conflicted::conflict_prefer("year", "data.table")
  conflicted::conflict_prefer("year", "lubridate")
  
  conflicted::conflict_prefer("month", "data.table")
  conflicted::conflict_prefer("month", "lubridate")
  
  conflicted::conflict_prefer("yday", "data.table")
  conflicted::conflict_prefer("yday", "lubridate")
  
  conflicted::conflict_prefer("first", "data.table")
  conflicted::conflict_prefer("first", "dplyr")
  
  # conflicted::conflict_prefer("filter", "dplyr")
  # conflicted::conflict_prefer("filter", "stats")
  
  # conflicted::conflict_prefer("filter", "dplyr")
  # conflicted::conflict_prefer("filter", "stats")
  
  conflicted::conflict_prefer("mutate", "plyr")
  conflicted::conflict_prefer("mutate", "dplyr")
  conflicted::conflict_prefer("rename", "plyr")
  conflicted::conflict_prefer("rename", "dplyr")
  conflicted::conflict_prefer("arrange", "plyr")
  conflicted::conflict_prefer("arrange", "dplyr")
  
  # Check
  conflicted::conflict_scout()


# # install.packages("maptools")
# library(move)
# library(tidyverse)
# library(maptools)
# # conflicted::conflict_prefer("filter", "dplyr")
# # conflicted::conflict_prefer("lag", "dplyr")
# # conflicted::conflict_prefer("select", "dplyr")
# # conflicted::conflict_prefer("summarise", "dplyr")
# library(lubridate)
# library(geosphere)
# library(glue)
# library(maps)
# library(plyr)
# # conflicted::conflict_prefer("map", "purrr")
# library(mapdata)
# library(raster)
# library(sp)
# library(rgdal)
# library(geosphere)
# library(dismo)
# library(rgeos)
# library(sf)
# library(recurse)
# library(plotly)
# # conflicted::conflict_prefer("layout", "plotly")
# # conflicted::conflict_prefer("collapse", "dplyr")
# library(leaftime)
# library(httr)
# library(jsonlite)
# library(leaflet)
# library(leafem)
# library(data.table)
# library(htmltools)
# # conflicted::conflict_prefer("span", "htmltools")
# library(leafpop)
# library(leaflet.extras)
# library(dplyr, warn.conflicts = FALSE)
# # 
# conflicted::conflict_prefer("config", "httr")
# conflicted::conflict_prefer("flatten", "purrr")
# conflicted::conflict_prefer("year", "data.table")
# conflicted::conflict_prefer("year", "lubridate")
# conflicted::conflict_prefer("yday", "data.table")
# conflicted::conflict_prefer("yday", "lubridate")
# conflicted::conflict_prefer("hour", "data.table")
# conflicted::conflict_prefer("hour", "lubridate")
# conflicted::conflict_prefer("month", "data.table")
# conflicted::conflict_prefer("month", "lubridate")
# conflicted::conflict_prefer("first", "data.table")
# conflicted::conflict_prefer("first", "dplyr")
# conflicted::conflict_prefer("rename", "plyr")
# conflicted::conflict_prefer("rename", "dplyr")

# conflicted::conflict_prefer_all("shinydashboardPlus", "shinydashboard")

# Check
# conflicted::conflict_scout()
}

# Run code ----------------------------------------------------------------
source("src/Import data.R")
#source("src/01_import and clean code using historical data.R") # <------------- use this if comms are really bad
rm(list = ls())
source("src/Add Metrics.R")
rm(list = ls())
source("src/Analyse Activity.R")
rm(list = ls())
source("src/Create clusters and prep map.R")
rm(list = ls())
source("src/Mapping.R")
rm(list = ls())
source("src/Activity Table.R")
rm(list = ls())
source("src/Summary maps.R")

#




